//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDesk.Gateway.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://webdesk.dealernet.com.br/WebDeskWF/aws_servdesk_demanda.aspx")]
        public string Gateway_WsGenexusDemanda_WS_ListarDemanda {
            get {
                return ((string)(this["Gateway_WsGenexusDemanda_WS_ListarDemanda"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://webdesk.dealernet.com.br/WebDeskWF/aws_servdesk_commit.aspx")]
        public string Gateway_WsGenexusSolucao_ws_servdesk_solucao {
            get {
                return ((string)(this["Gateway_WsGenexusSolucao_ws_servdesk_solucao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://webdesk.dealernet.com.br/WebDeskWF/aws_servdesk_demanda_objetos.aspx")]
        public string Gateway_WsGenexusUpdateDemanda_ws_servdesk_demanda_objetos {
            get {
                return ((string)(this["Gateway_WsGenexusUpdateDemanda_ws_servdesk_demanda_objetos"]));
            }
        }
    }
}
